# Generated by Django 3.0.2 on 2020-01-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='profile_photo',
            field=models.FileField(default=None, max_length=254, upload_to=None),
            preserve_default=False,
        ),
    ]
