# Generated by Django 3.0.2 on 2020-01-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_player_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='profile_photo',
            field=models.FileField(max_length=254, upload_to=''),
        ),
    ]
