# Generated by Django 3.0.2 on 2020-01-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_auto_20200110_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='profile_photo',
            field=models.CharField(max_length=254),
        ),
    ]
